#!/bin/sh
SD_MOUNTDIR="/tmp/sd"

log() { echo "*** $1" | busybox logger -t miicam_update; }
die() { log "$1" ; exit 1; }

log "*** Starting post update for mii update"

log "*** Creating new configuration file"
/tmp/sd/firmware/scripts/update/configupdate /tmp/sd/config.cfg

log "*** Triggering a reboot"
reboot
exit 0
