#!/bin/sh
SD_MOUNTDIR="/tmp/sd"

log() { echo "*** $1" | busybox logger -t miicam_update; }
die() { log "$1" ; exit 1; }

log "*** Starting preparation for mii update"

log "*** Freeing up memory by stopping all services"
for i in ${SD_MOUNTDIR}/firmware/init/S99* ;do
  [ "$i" == "${SD_MOUNTDIR}/firmware/init/S99dropbear" ] || \
  [ "$i" == "/tmp/sd/firmware/init/S99restore_state" ]   && continue
  $i stop
done

log "*** Copying rsync to /tmp/rsync"
cp /tmp/sd/firmware/bin/rsync /tmp/rsync

log "Backing up config.cfg"
cp /tmp/sd/config.cfg /tmp/config.old

