#!/bin/sh
INPUT="$1"
FILE="$2"

## Set the curl command depending on local or camera
if [ "$( uname -m )" == "armv5tel" ]
then
    CURL='curl --cacert /tmp/sd/firmware/etc/ssl/cacert.pem -qs '
else
    CURL='curl -qs '
fi

fileversion()
{
    local FILENAME="$1"

    ## Get version for web ui
    if [ -f "$FILENAME" ]
    then
        cat "$FILENAME" | jq -r '.tag'
        exit "$?"
    else
        echo "ERROR: Failed to retrieve current version from \"${FILENAME}\""
        exit 1
    fi
}


current()
{
    ## Get version for web ui
    fileversion "/tmp/sd/firmware/www/public/static/version.json"
}


nightly()
{
    ## Get the latest nightly build of the web interface from anaconda
    TAG="$( ${CURL} https://api.anaconda.org/package/MiiCam/MiiCamWeb/files | jq -r '. | to_entries[] .value.version'  | sort | tail -n 1 )"

    if [ "x$TAG" == "x" ]
    then
        echo "Tag not found!"
        exit 1
    else
        echo "$TAG"
        exit 0
    fi
}


latest()
{
    TAG="$( ${CURL} https://api.github.com/repos/miicam/miicamweb/releases/latest | jq -r '.tag_name' )"

    if [ "x$TAG" == "x" ]
    then
        echo "Tag not found!"
        exit 1
    else
        echo "$TAG"
        exit 0
    fi
}


usage()
{
    echo "Retrieve the latest or current version tag of the web ui"
    echo "Usage: $0 [--latest|--current|--nightly|--file]"
    exit 0
}


main()
{
    if [ "$INPUT" == "--current" ]
    then
        current
    elif [ "$INPUT" == "--nightly" ]
    then
        nightly
    elif [ "$INPUT" == "--latest" ]
    then
        latest
    elif [ "$INPUT" == "--file" ]
    then
        fileversion "${FILE}"
    else
        usage
    fi
}

main
