#!/bin/sh
INPUT="$1"
FILE="$2"

fileversion()
{
    local FILENAME="$1"

    ## Get version for web ui
    if [ -f "$FILENAME" ]
    then
        cat "$FILENAME" | jq -r '.tag'
        exit "$?"
    else
        echo "ERROR: Failed to retrieve current version from \"${FILENAME}\""
        exit 1
    fi
}



current()
{
    ## Get version for web ui
    fileversion "/tmp/sd/firmware/www/public/static/version.json"
}


latest()
{
    TAG="$( curl --cacert /tmp/sd/firmware/etc/ssl/cacert.pem -s https://api.github.com/repos/miicam/miicamweb/releases/latest | jq -r '.tag_name' )"

    if [ "x$TAG" == "x" ]
    then
        echo "Tag not found!"
        exit 1
    else
        echo "$TAG"
        exit 0
    fi
}


usage()
{
    echo "Retrieve the latest or current version tag of the web ui"
    echo "Usage: $0 [--latest|--current|--file]"
    exit 0
}


main()
{
    if [ "$INPUT" == "--current" ]
    then
        current
    elif [ "$INPUT" == "--latest" ]
    then
        latest
    elif [ "$INPUT" == "--file" ]
    then
        fileversion "${FILE}"
    else
        usage
    fi
}

main
