#!/bin/sh
TAG="$( git tag -l  | sort | tail -n 1 )"
COMMIT="$( git rev-parse --verify HEAD )"

DATESTAMP="$( date '+%Y.%m.%d' )"
TIMESTAMP="$( date '+%Y%m%d%H%M%S' )"

cat <<!
NAME=MiiCam
VERSION=$TAG
ID=$COMMIT
BUILDDATE=$DATESTAMP
BUILDTIME=$TIMESTAMP
HOME_URL="https://miicam.github.io/"
BUG_REPORT_URL="https://github.com/miicam/MiiCam/issues"
!
