#!/bin/sh
#
# Start the crond and crontab
#

SD_MOUNTDIR="/tmp/sd"
if [ -r "${SD_MOUNTDIR}/firmware/scripts/functions.sh" ]; then
  . "${SD_MOUNTDIR}/firmware/scripts/functions.sh"
else
  echo "Unable to load basic functions"
  exit 1
fi

NAME="crond"
DESC="Cron Daemon"
DAEMON="/usr/sbin/${NAME}"
DAEMON_OPTS="-c /var/run/cron"
PIDFILE="/var/run/${NAME}.pid"

load_crontab() {
    if [ -s "$SD_MOUNTDIR/firmware/etc/crontab" ]
    then
        ## Load crontab file
        crontab $DAEMON_OPTS $SD_MOUNTDIR/firmware/etc/crontab

        ## Execute all @reboot tasks
        grep '@reboot' $SD_MOUNTDIR/firmware/etc/crontab | sed -e 's/@reboot//g' | while read command
        do
            exec $command
        done
    fi
}

check_daemon_bin "${DAEMON}" "${DESC}"

case "$1" in
    start)
        mkdir -p /var/run/cron
        start_daemon_background
        load_crontab
    ;;
    stop)
        stop_daemon_background "${PIDFILE}"
    ;;
    restart|reload)
        "$0" stop
        "$0" start
    ;;
    status)
        status_daemon
    ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
    ;;
esac

exit $?
