#!/bin/sh
## purpose: Init script for dropbear SSH server
## license: GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html
## author: Jan Sperling , 2017

SD_MOUNTDIR="/tmp/sd"
if [ -r "${SD_MOUNTDIR}/firmware/scripts/functions.sh" ]
then
    . "${SD_MOUNTDIR}/firmware/scripts/functions.sh"
else
    echo "Unable to load basic functions"
    exit 1
fi

NAME="dropbear"
DESC="SSH server"
DAEMON="${SD_MOUNTDIR}/firmware/bin/${NAME}"
DAEMON_OPTS="-R -p 22 $DROPBEAR_EXTRA_ARGS"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="${LOGDIR}/${NAME}.log"

check_daemon_bin "${DAEMON}" "${DESC}"

recover_key() {
   if [ -d "${SD_MOUNTDIR}/firmware/etc/dropbear" ]
   then
       printf "*** Copying previous files to /etc/dropbear... "
       cp ${SD_MOUNTDIR}/firmware/etc/dropbear/* /etc/dropbear/
       ok_fail "$?"
   else
       printf "*** Generating a new SSH key for $NAME $DESC... "
       [ -f /etc/dropbear/dropbear_ecdsa_host_key ] && rm /etc/dropbear/dropbear_ecdsa_host_key
       ${SD_MOUNTDIR}/firmware/bin/dropbearkey -f /etc/dropbear/dropbear_ecdsa_host_key -t ecdsa
       ok_fail "$?"
   fi
}


save_key() {
    if [ ! -s "${SD_MOUNTDIR}/firmware/etc/dropbear/dropbear_ecdsa_host_key" ] && [ -s /etc/dropbear/dropbear_ecdsa_host_key ]
    then
        [ ! -d "${SD_MOUNTDIR}/firmware/etc/dropbear" ] && mkdir -p ${SD_MOUNTDIR}/firmware/etc/dropbear

        printf "*** Copying SSH key to sd card... "
        cp /etc/dropbear/dropbear_ecdsa_host_key "${SD_MOUNTDIR}/firmware/etc/dropbear/"
	    ok_fail "$?"
    fi
}


case "$1" in
  start)
        [ ! -d /etc/dropbear ] && mkdir -p /etc/dropbear

        ## Recover previous files from sdcard
        recover_key

        ## start the daemon
        start_daemon

        ## Save the key to the sdcard
        save_key
    ;;
  stop)
    stop_daemon
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  status)
    status_daemon
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $?
