#!/bin/sh
## purpose: Init script for FTP server
## license: GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html
## author: Jan Sperling , 2017

SD_MOUNTDIR="/tmp/sd"
if [ -r "${SD_MOUNTDIR}/firmware/scripts/functions.sh" ]; then
  . "${SD_MOUNTDIR}/firmware/scripts/functions.sh"
else
  echo "Unable to load basic functions"
  exit 1
fi

NAME="ftpd"
DESC="FTP server"
DAEMON="/usr/bin/tcpsvd"
DAEMON_OPTS="-vE 0.0.0.0 21 ftpd $FTP_ROOT $FTP_EXTRA_ARGUMENTS"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="${LOGDIR}/${NAME}.log"

check_daemon_bin "${DAEMON}" "${DESC}"

case "$1" in
  start)
    start_daemon_background
    ;;
  stop)
    stop_daemon_background
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  status)
    status_daemon
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $?
