#!/bin/sh
## purpose: Init script for lighttpd web server
## license: GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html
## author: Jan Sperling , 2017

SD_MOUNTDIR="/tmp/sd"
if [ -r "${SD_MOUNTDIR}/firmware/scripts/functions.sh" ]
then
    . "${SD_MOUNTDIR}/firmware/scripts/functions.sh"
else
    echo "Unable to load basic functions"
    exit 1
fi

NAME="lighttpd"
DESC="web server"
DAEMON="${SD_MOUNTDIR}/firmware/bin/${NAME}"
DAEMON_OPTS="-f ${SD_MOUNTDIR}/firmware/etc/lighttpd.conf"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="${LOGDIR}/${NAME}.log"

check_daemon_bin "${DAEMON}" "${DESC}"

case "$1" in
    start)
        [ ! -d "${SD_MOUNTDIR}/firmware/tmp" ] && mkdir -p "${SD_MOUNTDIR}/firmware/tmp"

        if [ ! -s "${SD_MOUNTDIR}/firmware/etc/lighttpd.user" ] || ! ( grep -q "^root" ${SD_MOUNTDIR}/firmware/etc/lighttpd.user )
        then
            echo "root:$ROOT_PASSWORD" >> "${SD_MOUNTDIR}/firmware/etc/lighttpd.user"
        fi

        start_daemon
    ;;
    stop)
        stop_daemon
    ;;
    restart|reload)
        "$0" stop
        "$0" start
    ;;
    status)
        status_daemon
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $?
