#!/bin/sh
## purpose: Init script for RTSP server
## license: GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html
## author: Jan Sperling , 2017

SD_MOUNTDIR="/tmp/sd"
if [ -r "${SD_MOUNTDIR}/firmware/scripts/functions.sh" ]; then
  . "${SD_MOUNTDIR}/firmware/scripts/functions.sh"
else
  echo "Unable to load basic functions"
  exit 1
fi

[ -z "$RTSP_FRAMERATE" ]    && RTSP_FRAMERATE=15
[ -z "$RTSP_WIDTH" ]        && RTSP_WIDTH=1280
[ -z "$RTSP_HEIGHT" ]       && RTSP_HEIGHT=720
[ -z "$RTSP_BITRATE" ]      && RTSP_BITRATE=8192
[ -z "$RTSP_BITRATE_MODE" ] && RTSP_BITRATE_MODE=4

NAME="rtspd"
DESC="RTSP server"
DAEMON="${SD_MOUNTDIR}/firmware/bin/${NAME}"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="${LOGDIR}/${NAME}.log"

DAEMON_OPTS=" -f$RTSP_FRAMERATE -w$RTSP_WIDTH -h$RTSP_HEIGHT -b$RTSP_BITRATE -m$RTSP_BITRATE_MODE $RTSP_EXTRA_ARGS"

## Enable motion detection
if [ "$MOTION_DETECTION" -eq 1 ] ; then
    DAEMON_OPTS="${DAEMON_OPTS} -d"
fi

## Enable take snapshot on motion
if [ "$MOTION_TAKE_SNAPSHOT" -eq 1 ] ; then
    DAEMON_OPTS="${DAEMON_OPTS} -s"
fi

## Enable record on motion
if [ "$MOTION_RECORD" -eq 1 ] ; then
    DAEMON_OPTS="${DAEMON_OPTS} -r"
fi

## export RTSP settings for subshells
if [ "x${RTSP_USER}" != "x" ] && [ "x${RTSP_PASS}" != "x" ]
then
    export RTSP_USER="${RTSP_USER}"
    export RTSP_PASS="${RTSP_PASS}"
fi

check_daemon_bin "${DAEMON}" "${DESC}"

case "$1" in
  start)
    start_daemon_background
    ;;
  stop)
    stop_daemon_background
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  status)
    status_daemon
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $?

