#!/bin/sh

SD_MOUNTDIR="/tmp/sd"
if [ -r "${SD_MOUNTDIR}/firmware/scripts/functions.sh" ]; then
  . "${SD_MOUNTDIR}/firmware/scripts/functions.sh"
else
  echo "Unable to load basic functions"
  exit 1
fi

NAME="telnetd"
DESC="Telnet Daemon"
DAEMON="/usr/sbin/${NAME}"
DAEMON_OPTS="-F"
PIDFILE="/var/run/${NAME}.pid"

check_daemon_bin "${DAEMON}" "${DESC}"

case "$1" in
  start)
	    start_daemon
        ;;
  stop)
	    stop_daemon
        ;;
  status)
        status_daemon
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
