#!/bin/sh
## purpose: Configure WiFi
## license: GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html
## author: Jan Sperling , 2017

SD_MOUNTDIR="/tmp/sd"
if [ -r "${SD_MOUNTDIR}/firmware/scripts/functions.sh" ]
then
    . "${SD_MOUNTDIR}/firmware/scripts/functions.sh"
else
    echo "Unable to load basic functions"
    exit 1
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
    cat << EOF
Usage of ${0} [<WIFI_SSID> [<WIFI_PASS>]]
Configure WiFi to connect to WIFI_SSID. WIFI_PASS is needed for WPA-PSK secured WiFis.
If no argument is given the values from config.cfg are used.
Otherwise the WiFi setup and config.cfg will be updated.
EOF
    exit
fi

if [ "$#" -ne 0 ]
then
    WIFI_SSID="${1}"
    WIFI_PASS="${2}"
fi

if [ -n "${WIFI_SSID}" ]
then
    echo "Configure WiFi"
    nvram_change=0

    if [ -z "${WIFI_PASS}" ]
    then
        WIFI_KEY_MGMT="NONE"
    else
        WIFI_KEY_MGMT="WPA"
    fi

    if [ "$(get_nvram miio_ssid)" != "${WIFI_SSID}" ]
    then
        set_nvram miio_ssid "${WIFI_SSID}"
    fi

    if [ "$(get_nvram miio_key_mgmt)" != "${WIFI_KEY_MGMT}" ]
    then
        set_nvram miio_key_mgmt "${WIFI_KEY_MGMT}"
    fi

    if [ "$(get_nvram miio_passwd)" != "${WIFI_PASS}" ]
    then
        set_nvram miio_passwd "${WIFI_PASS}"
    fi

    if [ "$(get_nvram wifi_ready)" != "yes" ]
    then
        set_nvram wifi_ready yes

        if pgrep wpa_supplicant > /dev/null
        then
            /mnt/data/imi/imi_init/S92wifi restart
        fi
    fi
fi

