#!/bin/sh
## purpose: Configure WiFi
## license: GPLv3+, http://www.gnu.org/licenses/gpl-3.0.html
## author: Jan Sperling , 2017

########################################
## Load functions                     ##
########################################

SD_MOUNTDIR="/tmp/sd"
if [ -r "${SD_MOUNTDIR}/firmware/scripts/functions.sh" ]
then
    . "${SD_MOUNTDIR}/firmware/scripts/functions.sh"
else
    echo "Unable to load basic functions"
    exit 1
fi

########################################
## Print help if -h is issued         ##
########################################

if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
    cat << EOF
Usage of ${0} [<WIFI_SSID> [<WIFI_PASS>]]
Configure WiFi to connect to WIFI_SSID. WIFI_PASS is needed for WPA-PSK secured WiFis.
If no argument is given the values from config.cfg are used.
EOF
    exit
fi

########################################
## Set password if given as command line arguments
########################################

if [ "$#" -ne 0 ]
then
    export WIFI_SSID="${1}"
    export WIFI_PASS="${2}"
fi

########################################
## Save wifi configuration to nvram   ##
########################################

if [ -n "${WIFI_SSID}" ]
then
    echo "*** Updating WIFI settings based on config.cfg"

    ## Set password or no password
    if [ -z "${WIFI_PASS}" ]
    then
        WIFI_KEY_MGMT="NONE"
    else
        WIFI_KEY_MGMT="WPA"
    fi

    ## Save SSID to nvram if changed or not set
    if [ "$( get_nvram miio_ssid )" != "${WIFI_SSID}" ]
    then
        set_nvram miio_ssid "${WIFI_SSID}"
    fi

    ## Set key mgmt if changed or not set
    if [ "$( get_nvram miio_key_mgmt )" != "${WIFI_KEY_MGMT}" ]
    then
        set_nvram miio_key_mgmt "${WIFI_KEY_MGMT}"
    fi

    ## Set password if changed or not set
    if [ "$(get_nvram miio_passwd )" != "${WIFI_PASS}" ]
    then
        set_nvram miio_passwd "${WIFI_PASS}"
    fi

    ## Change wifi_ready setting if not set
    if [ "$(get_nvram wifi_ready )" != "yes" ]
    then
        set_nvram wifi_ready yes

        if pgrep wpa_supplicant > /dev/null
        then
            /mnt/data/imi/imi_init/S92wifi restart
        fi
    fi
fi

